apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/anshuhtwt/Apache-Spark-App.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
