apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-app
  template:
    metadata:
      labels:
        app: spark-app
    spec:
      containers:
        - name: spark-app
          image: anshuhtwt/<image-name>
          ports:
            - containerPort: 8080

        
---


apiVersion: v1
kind: Service
metadata:
  name: spark-app-service
spec:
  selector:
    app: spark-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
